#!/bin/zsh

source ~/.zshrc

if [[ `ps ux | grep "rails server" | grep -v grep | wc -l` -gt 0 ]] ; then
  echo "Rails server is already running; launching console..."
  bin/rails console
else
  echo "Rails server is not running; launching server..."
  #bundle update
  bin/rails server
fi
